// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fneostfjaznxlotrcvam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZW9zdGZqYXpueGxvdHJjdmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTY5NDksImV4cCI6MjA2ODA3Mjk0OX0.A0Y4AbA9_BVx1aF8b6Y0f7VUik66z1Rp8SajJHJoNY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});