// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xectigebisfntlcoxqmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlY3RpZ2ViaXNmbnRsY294cW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjgwOTksImV4cCI6MjA2NzEwNDA5OX0.p6LtWfy4fh-yYEBnKT-Vagpify_1eiE1DlzonPhC4ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});